# Generated by Django 4.2 on 2024-01-10 00:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("detectmodel", "0005_remove_dangermodel_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dangermodel",
            options={"ordering": ("-pk",)},
        ),
        migrations.AlterField(
            model_name="dangermodel",
            name="image",
            field=models.ImageField(upload_to="media/"),
        ),
    ]
