# Generated by Django 4.2 on 2024-01-10 05:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("detectmodel", "0006_alter_dangermodel_options_alter_dangermodel_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="dangermodel",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2024, 1, 10, 5, 20, 12, 313968, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
