# Generated by Django 4.2 on 2024-01-11 04:44

import detectmodel.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("detectmodel", "0007_dangermodel_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dangermodel",
            name="image",
            field=models.ImageField(
                upload_to="media/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg"]
                    ),
                    detectmodel.models.validate_image_extension,
                ],
            ),
        ),
    ]
