# Generated by Django 4.2 on 2024-01-11 04:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("detectmodel", "0008_alter_dangermodel_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dangermodel",
            name="image",
            field=models.ImageField(
                upload_to="media/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg"]
                    )
                ],
            ),
        ),
    ]
